name: Elasticsearch Github Action

on: [push]

jobs:
  run-action:
    name: Start Elasticsearch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Start Elasticsearch
        uses: ./
        with:
          version: 7.6.1
          plugins: |
            https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.6.1/elasticsearch-analysis-ik-7.6.1.zip
            analysis-icu
            analysis-smartcn
            analysis-kuromoji


      - name: Elasticsearch is reachable
        run: |
          curl --verbose --show-error http://localhost:9200

  run-multiple-nodes:
    name: Start multiple Elasticsearch nodes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Start Elasticsearch
        uses: ./
        with:
          version: 7.6.1
          nodes: 3

      - name: Elasticsearch Node es1 is reachable
        run: |
          curl --verbose --show-error http://localhost:9200

      - name: Elasticsearch Node es2 is reachable
        run: |
          curl --verbose --show-error http://localhost:9201

      - name: Elasticsearch Node es3 is reachable
        run: |
          curl --verbose --show-error http://localhost:9202

      - name: All nodes joined the cluster
        run: |
          curl http://localhost:9200/_nodes/http?filter_path=nodes.*.name
